# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QDialog
from . import main_window

class Login_UI(QDialog):
    #new changes
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(80, 40, 261, 31))
        self.label.setObjectName("label")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(70, 220, 271, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.login_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.login_button.setObjectName("login_button")
        #newchanges
        self.horizontalLayout.addWidget(self.login_button)
        self.exit_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.exit_button.setObjectName("exit_button")
        self.horizontalLayout.addWidget(self.exit_button)
        self.gridLayoutWidget = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(70, 90, 271, 101))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.password_input = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.password_input.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText|QtCore.Qt.ImhSensitiveData)
        self.password_input.setText("")
        self.password_input.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_input.setObjectName("password_input")
        self.gridLayout.addWidget(self.password_input, 1, 1, 1, 1)
        self.label_username = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_username.setObjectName("label_username")
        self.gridLayout.addWidget(self.label_username, 0, 0, 1, 1)
        self.label_password = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_password.setObjectName("label_password")
        self.gridLayout.addWidget(self.label_password, 1, 0, 1, 1)
        self.username_input = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.username_input.setObjectName("username_input")
        self.gridLayout.addWidget(self.username_input, 0, 1, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Warehouse System Application"))
        self.login_button.setText(_translate("Dialog", "login"))
        self.exit_button.setText(_translate("Dialog", "exit"))
        self.label_username.setText(_translate("Dialog", "username"))
        self.label_password.setText(_translate("Dialog", "password"))

    # UI changes are above when update UI
    #---------------------------------------------
    # Add event listener to buttons
    def init(self):
        self.addEventListener(self)


    def addEventListener(self, Dialog):

        self.login_button.clicked.connect(self.handleLogin)



    #Add login handler
    def handleLogin(self, Dialog):
        if (self.username_input.text() == 'alicebob' and self.password_input.text() == '123456'):
            self.accept()

        else:
            QtWidgets.QMessageBox.warning(self, 'Error', 'Wrong username or password, retry!')
            #self.reject()